# Generated by Django 3.0.3 on 2020-03-03 17:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200301_2303'),
        ('profile', '0002_auto_20200303_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout")),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profile.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Product')),
            ],
            options={
                'verbose_name': 'ProductComment',
                'ordering': ['date'],
            },
        ),
    ]
