# Generated by Django 3.0.3 on 2020-03-06 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200301_2303'),
        ('profile', '0003_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('cp', models.CharField(max_length=5, null=True)),
                ('country', models.CharField(max_length=30)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
            ],
            options={
                'verbose_name': 'Address Customer',
                'ordering': ['firstName'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
                ('delivery', models.URLField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de debut de la commande')),
                ('endDate', models.DateTimeField(null=True, verbose_name='Date de fin de la commande')),
                ('methodPayment', models.CharField(max_length=15)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile.Address')),
            ],
            options={
                'verbose_name': 'Order Customer',
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['date'], 'verbose_name': 'Basket'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cp',
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
            options={
                'verbose_name': 'Order Customer Product',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile.Customer'),
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile.Customer'),
        ),
    ]
