# Generated by Django 3.0.3 on 2020-03-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20200306_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='endDate',
            field=models.DateTimeField(null=True, verbose_name='Date de fin de la commande'),
        ),
    ]
