# Generated by Django 3.0.3 on 2020-03-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20200306_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin de la commande'),
        ),
    ]
