# Generated by Django 3.0.3 on 2020-02-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date'], 'verbose_name': 'Product'},
        ),
        migrations.RemoveField(
            model_name='imgproduct',
            name='mainImage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
