# Generated by Django 3.0.3 on 2020-02-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200229_2044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgProduct',
        ),
    ]
