# Generated by Django 3.0.3 on 2020-02-29 20:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_delete_imgproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('use', models.BooleanField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout")),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='shop.Product')),
            ],
            options={
                'verbose_name': 'Images',
                'ordering': ['date'],
            },
        ),
    ]
