# Generated by Django 3.0.3 on 2020-03-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200229_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='use',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
