# Generated by Django 3.0.3 on 2020-03-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200301_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(null=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
