# Generated by Django 3.0.3 on 2020-03-01 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200301_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='star',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
