# Generated by Django 3.0.3 on 2020-03-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200301_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='alt',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
    ]
